### ISSUE TITLE
Compillation Error

### ISSUE THREAD

**Issue by drcryptographer** [bnb-chain/tss-lib#132]
When I want to use this library in my project, i got following errors @omershlo :

panic: proto: message KGRound1Message is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1a3b8a0, 0xc00007fc00, 0x1a27780, 0xc000516000, 0x1821440)
	C:/Users/achilless/go/pkg/mod/google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Types).register(0xc00015d800, 0x1835aca, 0x7, 0x1a3b8a0, 0xc00007fc00, 0x1821440, 0xc000151080, 0x13951ee, 0x1a3f3e0)
	C:/Users/achilless/go/pkg/mod/google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:566 +0x349
google.golang.org/protobuf/reflect/protoregistry.(*Types).RegisterMessage(0xc00015d800, 0x1a32c80, 0xc000151080, 0x0, 0x0)
	C:/Users/achilless/go/pkg/mod/google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:493 +0xfc
github.com/golang/protobuf/proto.RegisterType(0x1a324c0, 0x0, 0x18528a3, 0x2c)
	C:/Users/achilless/go/pkg/mod/github.com/golang/protobuf@v1.5.1/proto/registry.go:181 +0x78
github.com/binance-chain/tss-lib/ecdsa/keygen.init.2()
	C:/Users/achilless/go/pkg/mod/github.com/drcryptographer/tss-lib@v1.3.2/ecdsa/keygen/messages.go:36 +0x56

**Comment by PlamenHristov** [comment]
@drcryptographer I believe [#141](https://github.com/binance-chain/tss-lib/pull/141) fixed that. Let me know if the isseu is still happening
