### ISSUE TITLE
go vet issues 

### ISSUE THREAD

**Issue by momaee** [bnb-chain/tss-lib#163]
Hi there. I am using go vet in my repo. I get an error in the case of getting signature data at the final round of signing.

`assignment copies lock value to data: github.com/binance-chain/tss-lib/common.SignatureData contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex`

Also if you use your codes, you will get the same error in `https://github.com/bnb-chain/tss-lib/blob/30c5ee412a0ef9096ae37f67d6e0d5adcfdd551e/ecdsa/resharing/local_party_test.go#L209`

`ecdsa/resharing/local_party_test.go:209:20: copylocks: assignment copies lock value to signData: github.com/binance-chain/tss-lib/common.SignatureData contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)`

**Comment by yycen** [comment]
This PR could solve it. #167
