### ISSUE TITLE
Is PartyID.Key a secret?

### ISSUE THREAD

**Issue by typestring** [bnb-chain/tss-lib#179]
Hi
When creating a PartyID

```go
func NewPartyID(id, moniker string, key *big.Int) *PartyID {...}
```

should the value of `key` be treated as a secret? or is it just used as an identifier?

Thanks

**Comment by yycen** [comment]
This is not secret, the key is part of id of a party, it is used as the "x_i" where the polynomial in [Shamir's secret sharing](https://www.zkdocs.com/docs/zkdocs/protocol-primitives/shamir/) is evaluated.
