### ISSUE TITLE
Does this work OTB for Ethereum signing?

### ISSUE THREAD

**Issue by r4881t** [bnb-chain/tss-lib#189]
Many TSS Libs implement generic signing, and not Ethereum specific (RFC 6979, EIP 155 amongst others). I am wondering if this lib supports them out-of-the-box since it's presumably being used by the CLI.

**Comment by tangliang1** [comment]
pls ask if the RFC 6979 can be support?

**Comment by 7kms** [comment]
I am wondering if the RFC 6979 can be supported!
