### ISSUE TITLE
(question) have you addressed the attack in TS21?

### ISSUE THREAD

**Issue by weijiguo** [bnb-chain/tss-lib#214]
Alpha-Rays: Key Extraction Attacks on Threshold ECDSA Implementations

IACR ePrint Archive 2021/1621

**Comment by yshurik** [comment]
It says:
```
The only requirement for mounting a successful attack is to use a small Paillier encryption key. 
The key size check was not specified in the protocol and therefore missing from 
most existing threshold ECDSA implementations, making them vulnerable.
```

Should be matter to good checks of Paillier encryption key size to close this attack vector?

**Comment by weijiguo** [comment]
I don't get it. Are you leaving this to library users, or this check has been / will be implemented in the library?
