### ISSUE TITLE
How Can i use TSS for cosmos based chains ?

### ISSUE THREAD

**Issue by vishal-kanna** [bnb-chain/tss-lib#268]

**Comment by levischechter** [comment]
same way you do it with Bitcoin, Ethereum  etc. 
cosmos chains use secp256k1 curve.

**Comment by vishal-kanna** [comment]
Can you share me the docs for it

**Comment by levischechter** [comment]
There are no docs, but you can watch [This](https://github.com/bnb-chain/tss-lib/blob/master/ecdsa/keygen/local_party_test.go),
And the corresponding signing test file to figure out how to do it.

**Comment by vishal-kanna** [comment]
@levischechter  Thank you. As far I knew we have four steps for tss 
1.valut creation
2.keygen
3.signing
4 verification


I didn't find all these

**Comment by levischechter** [comment]
What do you mean by vault?
Keygen is the file i sent in the link.
Signing is in the same file in the signing folder.
Verification can be made with any ecdsa package. 
The public key, the message and the signature are public information so you can verify by yourself

**Comment by vishal-kanna** [comment]
@levischechter

**Comment by levischechter** [comment]
It's not part of the tss protocol.
The tss protocol consist of 3 methods:
1. Keygen
2. Signing
3. Resharing

You can find the examples for it in the test files I've mentioned.

**Comment by vishal-kanna** [comment]
Thank you @levischechter .Do we have docs for using TSS for bitcoin or ethereum

**Comment by levischechter** [comment]
Basically the steps are:
1. Do keygen
2. Get the address from public key using the specific Blockchain guides
3. Prepare message for signing
4. Sign the message
5. Broadcast the transaction with the signature to the Blockchain using the specific Blockchain format

**Comment by vishal-kanna** [comment]
I knew we have 3 steps 
1.Keygen
2.Signing 
3.Resharing

**Comment by levischechter** [comment]
you need to be more specific with your question.

**Comment by vishal-kanna** [comment]
How to use Tss for signing a cosmos based transaction

**Comment by levischechter** [comment]
do you have the massage you wanna sign already? or you still struggle with the message preparing stage?
NOTE: by message I mean the raw byte of the transaction you need to sign.

**Comment by vishal-kanna** [comment]
Think of a message "hello" or any message .Now i want to use TSS for signing it

**Comment by levischechter** [comment]
I already sent you an example.
[signing example](https://github.com/bnb-chain/tss-lib/blob/b8d526df3275a545e62694f3f30989d9f3b85cd9/ecdsa/signing/local_party_test.go#L38)
