### ISSUE TITLE
Wrong bip32 version for ExtendedKey

### ISSUE THREAD

**Issue by zargarzadehm** [bnb-chain/tss-lib#288]
https://github.com/bnb-chain/tss-lib/blob/7113b68867a703940aa0c2150fa80ea63ab8d07b/ecdsa/signing/key_derivation_util.go#L55

Is there a specific reason for setting `HDPrivateKeyID` as the Version for the extended PublicKey in the function `derivingPubkeyFromPath`? It seems like it should be `HDPublicKeyID`.

```
	extendedParentPk := &ckd.ExtendedKey{
		PublicKey:  pk,
		Depth:      0,
		ChildIndex: 0,
		ChainCode:  chainCode[:],
		ParentFP:   []byte{0x00, 0x00, 0x00, 0x00},
		Version:    net.HDPublicKeyID[:],
	}
```

For instance, in [this unit test](https://github.com/bnb-chain/tss-lib/blob/7113b68867a703940aa0c2150fa80ea63ab8d07b/ecdsa/signing/local_party_test.go#L244), you are deriving using `keys[0].ECDSAPub`, while the Version set in `derivingPubkeyFromPath` is `HDPrivateKeyID`, which implies the response would involve `xprv` instead of `xpub`.

**Comment by yycen** [comment]
Hi @zargarzadehm, there could be some misuse of the field. But currently the (non-hardened) child key derivation only use the publickey, chainocode to compute next level child, the version seems not impact anywhere. I guess the whole structure kept mainly to be compatible with test suite from e.g. btcsuite

**Comment by zargarzadehm** [comment]
> Hi @zargarzadehm, there could be some misuse of the field. But currently the (non-hardened) child key derivation only use the publickey, chainocode to compute next level child, the version seems not impact anywhere. I guess the whole structure kept mainly to be compatible with test suite from e.g. btcsuite

Do you mean for production purpose we should use [DeriveChildKeyFromHierarchy](https://github.com/bnb-chain/tss-lib/blob/7113b68867a703940aa0c2150fa80ea63ab8d07b/crypto/ckd/child_key_derivation.go#L183) method directly, instead of `derivingPubkeyFromPath`?
