### ISSUE TITLE
Problem with ecdsa signing using NewLocalPartyWithKDD

### ISSUE THREAD

**Issue by zargarzadehm** [bnb-chain/tss-lib#293]
Hi

I'm trying to use ecdsa singing with `NewLocalPartyWithKDD` but I'm getting this error in round 9:
``` 
party {0,tssPeer/12D3KooWCRHb4wfTxxvTKEqgDzgx7YMvyZccJKKG1zxVBUN3T5dq}, round 9, culprits [{0,tssPeer/12D3KooWCRHb4wfTxxvTKEqgDzgx7YMvyZccJKKG1zxVBUN3T5dq}]: U doesn't equal T
```

Do you have any suggestions? Which parameters in creating a party can affect the verification in round 9?

**Comment by yycen** [comment]
Hi
Do you use the same msg to initialize NewLocalParty*(msg, ...) ? If the message to sign is not the same across all signing parties, it could possibly result in the error in round 9.

**Comment by zargarzadehm** [comment]
I checked that the message should be the same for all parties. I also tested using `NewLocalParty` instead of `NewLocalPartyWithKDD` (without key derivation), and the message was signed successfully. The issue arises when attempting to sign using `NewLocalPartyWithKDD`.

**Comment by zargarzadehm** [comment]
> Hi Do you use the same msg to initialize NewLocalParty*(msg, ...) ? If the message to sign is not the same across all signing parties, it could possibly result in the error in round 9.

I checked that the message should be the same for all parties. I also tested using `NewLocalParty` instead of `NewLocalPartyWithKDD` (without key derivation), and the message was signed successfully. The issue arises when attempting to sign using `NewLocalPartyWithKDD`.

**Comment by yycen** [comment]
Did you call UpdatePublicKeyAndAdjustBigXj?
For a given keyDelta value, it should be noticed that the corresponding child pubkey is needed to feed in

```
    keyDerivationDelta := big.NewInt(123)

    deltaG := crypto.ScalarBaseMult(tss.S256(), keyDerivationDelta)
    cPk, err := deltaG.Add(keys[0].ECDSAPub)
    cPubKey := ecdsa.PublicKey{
        Curve: btcec.S256(),
        X:     cPk.X(),
        Y:     cPk.Y(),
    }
    err = UpdatePublicKeyAndAdjustBigXj(keyDerivationDelta, keys, &cPubKey, tss.S256())
```

**Comment by zargarzadehm** [comment]
> Did you call UpdatePublicKeyAndAdjustBigXj? For a given keyDelta value, it should be noticed that the corresponding child pubkey is needed to feed in
> 
> ```
>     keyDerivationDelta := big.NewInt(123)
> 
>     deltaG := crypto.ScalarBaseMult(tss.S256(), keyDerivationDelta)
>     cPk, err := deltaG.Add(keys[0].ECDSAPub)
>     cPubKey := ecdsa.PublicKey{
>         Curve: btcec.S256(),
>         X:     cPk.X(),
>         Y:     cPk.Y(),
>     }
>     err = UpdatePublicKeyAndAdjustBigXj(keyDerivationDelta, keys, &cPubKey, tss.S256())
> ```

Thank you for your assistance; my issue was related to updating the reference keys.

As a suggestion, I believe that `UpdatePublicKeyAndAdjustBigXj` should be called for a single key rather than a list of keys. In production use, each user should call this function with their key, which should be passed as a pointer.

**Comment by franOlea** [comment]
Hi @zargarzadehm , could you share a little more about your issue and what you did to fix it? I'm currently facing the same error and while I understand yycen's suggestion above (and checked I'm doing this right) I'm not sure I understand what you mean by updating reference keys. Could you expand on this?

Thanks!

**Comment by zargarzadehm** [comment]
> Hi @zargarzadehm , could you share a little more about your issue and what you did to fix it? I'm currently facing the same error and while I understand yycen's suggestion above (and checked I'm doing this right) I'm not sure I understand what you mean by updating reference keys. Could you expand on this?
> 
> Thanks!

Hey, sorry for the late response. Has your issue been resolved?

**Comment by zargarzadehm** [comment]
@franOlea Take a look at my [code](https://github.com/zargarzadehm/sign-protocols/blob/d45371de96365f414844a10bc39db896700e418a/services/tss-api/app/sign/ecdsa/ecdsa.go#L197), especially the deep clone line. My problem was related to changing the reference value of my list during the derivation key.
